/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisitorsIndexRouteImport } from './routes/visitors/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as ChatbotIndexRouteImport } from './routes/chatbot/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardFormRouteImport } from './routes/dashboard/form'
import { Route as DashboardFaqsRouteImport } from './routes/dashboard/faqs'
import { Route as DashboardDataTableRouteImport } from './routes/dashboard/data-table'
import { Route as ApiDemoRouteImport } from './routes/api/demo'
import { Route as ApiAiRouteImport } from './routes/api/ai'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as DashboardSubjectsIndexRouteImport } from './routes/dashboard/subjects/index'
import { Route as DashboardSubjectsLessonIndexRouteImport } from './routes/dashboard/subjects/lesson/index'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitorsIndexRoute = VisitorsIndexRouteImport.update({
  id: '/visitors/',
  path: '/visitors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ChatbotIndexRoute = ChatbotIndexRouteImport.update({
  id: '/chatbot/',
  path: '/chatbot/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFormRoute = DashboardFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardFaqsRoute = DashboardFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDataTableRoute = DashboardDataTableRouteImport.update({
  id: '/data-table',
  path: '/data-table',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiDemoRoute = ApiDemoRouteImport.update({
  id: '/api/demo',
  path: '/api/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/_auth/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/_auth/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSubjectsIndexRoute = DashboardSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSubjectsLessonIndexRoute =
  DashboardSubjectsLessonIndexRouteImport.update({
    id: '/subjects/lesson/',
    path: '/subjects/lesson/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/api/ai': typeof ApiAiRoute
  '/api/demo': typeof ApiDemoRoute
  '/dashboard/data-table': typeof DashboardDataTableRoute
  '/dashboard/faqs': typeof DashboardFaqsRoute
  '/dashboard/form': typeof DashboardFormRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/chatbot': typeof ChatbotIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/visitors': typeof VisitorsIndexRoute
  '/dashboard/subjects': typeof DashboardSubjectsIndexRoute
  '/dashboard/subjects/lesson': typeof DashboardSubjectsLessonIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/api/ai': typeof ApiAiRoute
  '/api/demo': typeof ApiDemoRoute
  '/dashboard/data-table': typeof DashboardDataTableRoute
  '/dashboard/faqs': typeof DashboardFaqsRoute
  '/dashboard/form': typeof DashboardFormRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/chatbot': typeof ChatbotIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/visitors': typeof VisitorsIndexRoute
  '/dashboard/subjects': typeof DashboardSubjectsIndexRoute
  '/dashboard/subjects/lesson': typeof DashboardSubjectsLessonIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/api/ai': typeof ApiAiRoute
  '/api/demo': typeof ApiDemoRoute
  '/dashboard/data-table': typeof DashboardDataTableRoute
  '/dashboard/faqs': typeof DashboardFaqsRoute
  '/dashboard/form': typeof DashboardFormRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/chatbot/': typeof ChatbotIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/visitors/': typeof VisitorsIndexRoute
  '/dashboard/subjects/': typeof DashboardSubjectsIndexRoute
  '/dashboard/subjects/lesson/': typeof DashboardSubjectsLessonIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/api/ai'
    | '/api/demo'
    | '/dashboard/data-table'
    | '/dashboard/faqs'
    | '/dashboard/form'
    | '/dashboard/settings'
    | '/chatbot'
    | '/dashboard/'
    | '/projects'
    | '/visitors'
    | '/dashboard/subjects'
    | '/dashboard/subjects/lesson'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/api/ai'
    | '/api/demo'
    | '/dashboard/data-table'
    | '/dashboard/faqs'
    | '/dashboard/form'
    | '/dashboard/settings'
    | '/chatbot'
    | '/dashboard'
    | '/projects'
    | '/visitors'
    | '/dashboard/subjects'
    | '/dashboard/subjects/lesson'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/_auth/forgot-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/api/ai'
    | '/api/demo'
    | '/dashboard/data-table'
    | '/dashboard/faqs'
    | '/dashboard/form'
    | '/dashboard/settings'
    | '/chatbot/'
    | '/dashboard/'
    | '/projects/'
    | '/visitors/'
    | '/dashboard/subjects/'
    | '/dashboard/subjects/lesson/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  ApiAiRoute: typeof ApiAiRoute
  ApiDemoRoute: typeof ApiDemoRoute
  ChatbotIndexRoute: typeof ChatbotIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  VisitorsIndexRoute: typeof VisitorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitors/': {
      id: '/visitors/'
      path: '/visitors'
      fullPath: '/visitors'
      preLoaderRoute: typeof VisitorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/chatbot/': {
      id: '/chatbot/'
      path: '/chatbot'
      fullPath: '/chatbot'
      preLoaderRoute: typeof ChatbotIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/form': {
      id: '/dashboard/form'
      path: '/form'
      fullPath: '/dashboard/form'
      preLoaderRoute: typeof DashboardFormRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/faqs': {
      id: '/dashboard/faqs'
      path: '/faqs'
      fullPath: '/dashboard/faqs'
      preLoaderRoute: typeof DashboardFaqsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/data-table': {
      id: '/dashboard/data-table'
      path: '/data-table'
      fullPath: '/dashboard/data-table'
      preLoaderRoute: typeof DashboardDataTableRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/demo': {
      id: '/api/demo'
      path: '/api/demo'
      fullPath: '/api/demo'
      preLoaderRoute: typeof ApiDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/subjects/': {
      id: '/dashboard/subjects/'
      path: '/subjects'
      fullPath: '/dashboard/subjects'
      preLoaderRoute: typeof DashboardSubjectsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/subjects/lesson/': {
      id: '/dashboard/subjects/lesson/'
      path: '/subjects/lesson'
      fullPath: '/dashboard/subjects/lesson'
      preLoaderRoute: typeof DashboardSubjectsLessonIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardDataTableRoute: typeof DashboardDataTableRoute
  DashboardFaqsRoute: typeof DashboardFaqsRoute
  DashboardFormRoute: typeof DashboardFormRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSubjectsIndexRoute: typeof DashboardSubjectsIndexRoute
  DashboardSubjectsLessonIndexRoute: typeof DashboardSubjectsLessonIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDataTableRoute: DashboardDataTableRoute,
  DashboardFaqsRoute: DashboardFaqsRoute,
  DashboardFormRoute: DashboardFormRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSubjectsIndexRoute: DashboardSubjectsIndexRoute,
  DashboardSubjectsLessonIndexRoute: DashboardSubjectsLessonIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  ApiAiRoute: ApiAiRoute,
  ApiDemoRoute: ApiDemoRoute,
  ChatbotIndexRoute: ChatbotIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  VisitorsIndexRoute: VisitorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
